name: cmake-build

on:
  push:
    branches: [ Main ]
  pull_request:
    branches: [ Main ]
  workflow_dispatch:

env:
  VCPKG_FILE: c:/vcpkg/scripts/buildsystems/vcpkg.cmake

jobs:
  download-build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and extract Rhino SDK
        id: rhino_sdk
        uses: ./.github/actions/rhino-sdk

      - name: Configure CMake project
        run: |
          $sdkRoot = "${{ steps.rhino_sdk.outputs.sdkRoot }}"
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DRHINO_DEBUG_PLUGIN=OFF -DRHINOSDK_ROOT="$sdkRoot"
        shell: pwsh
        working-directory: ${{ github.workspace }}
 
      - name: Build CMake project
        run: cmake --build build --config Release


