name: Build Cookiecutter Template

# FIXME: adjsut when to fire this one
on:
  push:
    branches: [ Main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PAT
        run: git remote set-url origin https://x-access-token:${{ secrets.ADMIN_CICD_TOKEN }}@github.com/9and3/cmake4rhino.git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install cookiecutter

      - name: Copy and template files
        run: |
          mkdir template
          rsync -a --exclude '.git' ./ template/
          cd template
          
          # Replace all occurrences in file contents
          find . -type f -exec sed -i 's/cmake4rhino/{{cookiecutter.project_slug}}/g' {} +
          # Rename files and folders: cmake4rhino* -> {{cookiecutter.project_slug}}*
          find . -depth -name '*cmake4rhino*' -exec bash -c '
            src="$0"
            dst=$(echo "$src" | sed "s/cmake4rhino/{{cookiecutter.project_slug}}/g")
            mv "$src" "$dst"
          ' {} \;

          # Add cookiecutter.json (no trailing comma)
          echo '{
            "project_slug": "cmake4rhino",
            "plugin_name": "cmake4rhino_cookiecutter"
          }' > cookiecutter.json

          # Move all files except cookiecutter.json into the project_slug directory
          mkdir -p "{{cookiecutter.project_slug}}"
          shopt -s extglob
          mv !(cookiecutter.json|{{cookiecutter.project_slug}}) "{{cookiecutter.project_slug}}"/

      - name: Commit and push to cookietemplate branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B cookietemplate
          git rm -rf .
          cp -r template/* .
          git add .
          git commit -m "Build Cookiecutter template from main"
          git push --force origin cookietemplate

